import 'package:flutter/material.dart';

const String _defaultLocaleCode = 'en';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('ja'),
    Locale('ru'),
    Locale('es'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app.title': 'VADA Admin',
      'auth.loginTitle': 'Admin Login',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.login': 'Login',
      'auth.loggingIn': 'Logging in...',
      'auth.invalidRole': 'Your account is not an admin.',
      'auth.signOut': 'Sign out',
      'auth.welcome': 'Welcome back',
      'auth.loginFailed': 'Login failed. Please check credentials.',
      'nav.dashboard': 'Dashboard',
      'nav.fighters': 'Fighters',
      'nav.contacts': 'Contacts',
      'nav.locations': 'Locations',
      'nav.whereabouts': 'Whereabouts',
      'nav.checkins': 'Check-ins',
      'nav.notifications': 'Notifications',
      'nav.reports': 'Reports',
      'nav.settings': 'Settings',
      'nav.language': 'Language',
      'dashboard.title': 'Admin Dashboard',
      'dashboard.subtitle': 'Manage fighters and platform data.',
      'dashboard.heroTitle': 'Operational Command Center',
      'dashboard.heroSubtitle':
          'Track athlete records, whereabouts flow, and testing operations from one place.',
      'dashboard.quickStats': 'Quick Stats',
      'dashboard.dataOverviewTitle': 'Data Overview',
      'dashboard.keyOperations': 'Key Operations',
      'dashboard.visualInsights': 'Visual Insights',
      'dashboard.fighterStatusChart': 'Fighter Status Distribution',
      'dashboard.recordsByModule': 'Records by Module',
      'dashboard.noChartData': 'No chart data yet.',
      'dashboard.totalFighters': 'Total fighters',
      'dashboard.activeFighters': 'Active fighters',
      'dashboard.disabledFighters': 'Disabled fighters',
      'dashboard.schedules': 'Schedules',
      'dashboard.scheduleRequests': 'Schedule Change Requests',
      'dashboard.manageFightersHint':
          'Use fighter management to create accounts and control access.',
      'dashboard.goToFighters': 'Go to Fighters',
      'dashboard.recentFighters': 'Recently updated fighters',
      'dashboard.noRecentFighters': 'No fighter activity yet.',
      'fighters.title': 'Fighter Management',
      'fighters.create': 'Create Fighter',
      'fighters.edit': 'Edit',
      'fighters.save': 'Save',
      'fighters.cancel': 'Cancel',
      'fighters.empty': 'No fighters found yet.',
      'fighters.loading': 'Loading fighters...',
      'fighters.error': 'Could not load fighters.',
      'fighters.enabled': 'Enabled',
      'fighters.disabled': 'Disabled',
      'fighters.status': 'Status',
      'fighters.actions': 'Actions',
      'fighters.account': 'Account Access',
      'fighters.createSuccess': 'Fighter account created successfully.',
      'fighters.updateSuccess': 'Fighter updated successfully.',
      'fighters.fullName': 'Full Name',
      'fighters.dateOfBirth': 'Date of Birth',
      'fighters.selectDate': 'Select date of birth',
      'fighters.invalidDate': 'Please select a valid date.',
      'fighters.futureDob': 'Date of birth cannot be in the future.',
      'fighters.minAge': 'Fighter must be at least 12 years old.',
      'fighters.unrealisticDob': 'Date of birth looks invalid.',
      'fighters.gender': 'Gender',
      'fighters.genderMale': 'Male',
      'fighters.genderFemale': 'Female',
      'fighters.genderOther': 'Other',
      'fighters.phone': 'Phone',
      'fighters.email': 'Email',
      'fighters.address': 'Address',
      'fighters.primaryContact': 'Primary Contact Person',
      'fighters.password': 'Temporary Password',
      'fighters.required': 'Please fill all required fields.',
      'fighters.unknownError': 'An unexpected error occurred.',
      'fighters.noResults': 'No fighters match the current filters.',
      'fighters.clearFilters': 'Clear filters',
      'fighters.searchPlaceholder': 'Search by name, email, or phone',
      'contacts.title': 'Contacts Management',
      'contacts.add': 'Add Contact',
      'contacts.edit': 'Edit Contact',
      'contacts.name': 'Name',
      'contacts.phone': 'Phone',
      'contacts.email': 'Email',
      'contacts.address': 'Address',
      'contacts.role': 'Role',
      'contacts.actions': 'Actions',
      'contacts.search': 'Search contacts',
      'contacts.loading': 'Loading contacts...',
      'contacts.error': 'Could not load contacts.',
      'contacts.empty': 'No contacts found yet.',
      'contacts.noResults': 'No contacts match the current filters.',
      'contacts.createSuccess': 'Contact created successfully.',
      'contacts.updateSuccess': 'Contact updated successfully.',
      'contacts.unknownError': 'An unexpected error occurred.',
      'contacts.roleTrainer': 'Trainer',
      'contacts.roleManager': 'Manager',
      'contacts.rolePromoter': 'Promoter',
      'contacts.roleOther': 'Other',
      'locations.title': 'Locations Management',
      'locations.add': 'Add Location',
      'locations.edit': 'Edit Location',
      'locations.name': 'Name',
      'locations.address': 'Address',
      'locations.type': 'Location Type',
      'locations.assignedFighters': 'Assigned Fighters',
      'locations.actions': 'Actions',
      'locations.search': 'Search locations',
      'locations.loading': 'Loading locations...',
      'locations.error': 'Could not load locations.',
      'locations.empty': 'No locations found yet.',
      'locations.noResults': 'No locations match the current filters.',
      'locations.createSuccess': 'Location created successfully.',
      'locations.updateSuccess': 'Location updated successfully.',
      'locations.unknownError': 'An unexpected error occurred.',
      'locations.typeTesting': 'Testing location',
      'locations.typeTraining': 'Training location',
      'locations.typeEvent': 'Event location',
      'locations.unassigned': 'Unassigned',
      'locations.noFighters': 'No fighters available for assignment.',
      'whereabouts.title': 'Whereabouts Management',
      'whereabouts.add': 'Add Whereabouts Entry',
      'whereabouts.edit': 'Edit Whereabouts Entry',
      'whereabouts.search': 'Search whereabouts',
      'whereabouts.loading': 'Loading whereabouts entries...',
      'whereabouts.error': 'Could not load whereabouts entries.',
      'whereabouts.empty': 'No whereabouts entries found yet.',
      'whereabouts.noResults': 'No whereabouts entries match the filters.',
      'whereabouts.createSuccess': 'Whereabouts entry created successfully.',
      'whereabouts.updateSuccess': 'Whereabouts entry updated successfully.',
      'whereabouts.unknownError': 'An unexpected error occurred.',
      'whereabouts.fighter': 'Fighter',
      'whereabouts.date': 'Date',
      'whereabouts.time': 'Time',
      'whereabouts.startTime': 'Start Time',
      'whereabouts.endTime': 'End Time',
      'whereabouts.location': 'Location',
      'whereabouts.contact': 'Contact',
      'whereabouts.recurrence': 'Recurrence',
      'whereabouts.daily': 'Daily',
      'whereabouts.weekly': 'Weekly',
      'whereabouts.monthly': 'Monthly',
      'whereabouts.notes': 'Notes',
      'whereabouts.actions': 'Actions',
      'whereabouts.na': 'N/A',
      'whereabouts.invalidTime': 'End time must be later than start time.',
      'common.comingSoon': 'Coming soon',
      'common.retry': 'Retry',
      'common.loading': 'Loading...',
      'comingSoon.contacts':
          'Contacts management is part of a later milestone and will be available soon.',
      'comingSoon.locations':
          'Locations management is part of a later milestone and will be available soon.',
      'comingSoon.whereabouts':
          'Whereabouts monitoring is part of a later milestone and will be available soon.',
      'comingSoon.checkins':
          'Check-in monitoring is part of a later milestone and will be available soon.',
      'comingSoon.notifications':
          'Notification monitoring is part of a later milestone and will be available soon.',
      'comingSoon.reports':
          'Reports are part of a later milestone and will be available soon.',
      'comingSoon.settings':
          'Settings is part of a later milestone and will be available soon.',
    },
    'ja': {
      'app.title': 'VADA 管理',
      'auth.loginTitle': '管理者ログイン',
      'auth.email': 'メールアドレス',
      'auth.password': 'パスワード',
      'auth.login': 'ログイン',
      'auth.loggingIn': 'ログイン中...',
      'auth.invalidRole': 'このアカウントは管理者ではありません。',
      'auth.signOut': 'ログアウト',
      'auth.welcome': 'おかえりなさい',
      'auth.loginFailed': 'ログインに失敗しました。認証情報を確認してください。',
      'nav.dashboard': 'ダッシュボード',
      'nav.fighters': '選手',
      'nav.contacts': '連絡先',
      'nav.locations': 'ロケーション',
      'nav.whereabouts': '所在情報',
      'nav.checkins': 'チェックイン',
      'nav.notifications': '通知',
      'nav.reports': 'レポート',
      'nav.settings': '設定',
      'nav.language': '言語',
      'dashboard.title': '管理ダッシュボード',
      'dashboard.subtitle': '選手とプラットフォームデータを管理します。',
      'dashboard.quickStats': '概要',
      'dashboard.dataOverviewTitle': 'データ概要',
      'dashboard.totalFighters': '選手数',
      'dashboard.activeFighters': '有効な選手',
      'dashboard.disabledFighters': '無効な選手',
      'dashboard.manageFightersHint': '選手管理でアカウント作成とアクセス制御を行えます。',
      'dashboard.goToFighters': '選手管理へ',
      'dashboard.recentFighters': '最近更新された選手',
      'dashboard.noRecentFighters': '選手アクティビティはまだありません。',
      'fighters.title': '選手管理',
      'fighters.create': '選手を作成',
      'fighters.edit': '編集',
      'fighters.save': '保存',
      'fighters.cancel': 'キャンセル',
      'fighters.empty': '選手がまだ登録されていません。',
      'fighters.loading': '選手データを読み込み中...',
      'fighters.error': '選手データを読み込めません。',
      'fighters.enabled': '有効',
      'fighters.disabled': '無効',
      'fighters.status': '状態',
      'fighters.actions': '操作',
      'fighters.account': 'ログインアクセス',
      'fighters.createSuccess': '選手アカウントを作成しました。',
      'fighters.updateSuccess': '選手情報を更新しました。',
      'fighters.fullName': '氏名',
      'fighters.dateOfBirth': '生年月日',
      'fighters.selectDate': '生年月日を選択',
      'fighters.invalidDate': '正しい日付を選択してください。',
      'fighters.futureDob': '生年月日に未来の日付は使えません。',
      'fighters.minAge': '選手は12歳以上である必要があります。',
      'fighters.unrealisticDob': '生年月日が不正です。',
      'fighters.gender': '性別',
      'fighters.genderMale': '男性',
      'fighters.genderFemale': '女性',
      'fighters.genderOther': 'その他',
      'fighters.phone': '電話番号',
      'fighters.email': 'メール',
      'fighters.address': '住所',
      'fighters.primaryContact': '主連絡先',
      'fighters.password': '仮パスワード',
      'fighters.required': '必須項目を入力してください。',
      'fighters.unknownError': '予期しないエラーが発生しました。',
      'fighters.noResults': '現在のフィルターに一致する選手がいません。',
      'fighters.clearFilters': 'フィルターをクリア',
      'fighters.searchPlaceholder': '名前・メール・電話で検索',
      'contacts.title': '連絡先管理',
      'contacts.add': '連絡先を追加',
      'contacts.edit': '連絡先を編集',
      'contacts.name': '名前',
      'contacts.phone': '電話番号',
      'contacts.email': 'メール',
      'contacts.address': '住所',
      'contacts.role': '役割',
      'contacts.actions': '操作',
      'contacts.search': '連絡先を検索',
      'contacts.loading': '連絡先を読み込み中...',
      'contacts.error': '連絡先を読み込めません。',
      'contacts.empty': '連絡先がまだありません。',
      'contacts.noResults': '条件に一致する連絡先がありません。',
      'contacts.createSuccess': '連絡先を作成しました。',
      'contacts.updateSuccess': '連絡先を更新しました。',
      'contacts.unknownError': '予期しないエラーが発生しました。',
      'contacts.roleTrainer': 'トレーナー',
      'contacts.roleManager': 'マネージャー',
      'contacts.rolePromoter': 'プロモーター',
      'contacts.roleOther': 'その他',
      'locations.title': 'ロケーション管理',
      'locations.add': 'ロケーションを追加',
      'locations.edit': 'ロケーションを編集',
      'locations.name': '名前',
      'locations.address': '住所',
      'locations.type': 'ロケーション種別',
      'locations.assignedFighters': '割り当てられた選手',
      'locations.actions': '操作',
      'locations.search': 'ロケーションを検索',
      'locations.loading': 'ロケーションを読み込み中...',
      'locations.error': 'ロケーションを読み込めません。',
      'locations.empty': 'ロケーションがまだありません。',
      'locations.noResults': '条件に一致するロケーションがありません。',
      'locations.createSuccess': 'ロケーションを作成しました。',
      'locations.updateSuccess': 'ロケーションを更新しました。',
      'locations.unknownError': '予期しないエラーが発生しました。',
      'locations.typeTesting': '検査ロケーション',
      'locations.typeTraining': 'トレーニングロケーション',
      'locations.typeEvent': 'イベントロケーション',
      'locations.unassigned': '未割り当て',
      'locations.noFighters': '割り当て可能な選手がいません。',
      'common.comingSoon': '近日公開',
      'common.retry': '再試行',
      'common.loading': '読み込み中...',
      'comingSoon.contacts': '連絡先管理は後続マイルストーンで提供予定です。',
      'comingSoon.locations': 'ロケーション管理は後続マイルストーンで提供予定です。',
      'comingSoon.whereabouts': '所在情報監視は後続マイルストーンで提供予定です。',
      'comingSoon.checkins': 'チェックイン監視は後続マイルストーンで提供予定です。',
      'comingSoon.notifications': '通知監視は後続マイルストーンで提供予定です。',
      'comingSoon.reports': 'レポートは後続マイルストーンで提供予定です。',
      'comingSoon.settings': '設定は後続マイルストーンで提供予定です。',
    },
    'ru': {
      'app.title': 'VADA Админ',
      'auth.loginTitle': 'Вход администратора',
      'auth.email': 'Email',
      'auth.password': 'Пароль',
      'auth.login': 'Войти',
      'auth.loggingIn': 'Выполняется вход...',
      'auth.invalidRole': 'У вашей учетной записи нет прав администратора.',
      'auth.signOut': 'Выйти',
      'auth.welcome': 'С возвращением',
      'auth.loginFailed': 'Не удалось войти. Проверьте данные.',
      'nav.dashboard': 'Панель',
      'nav.fighters': 'Бойцы',
      'nav.contacts': 'Контакты',
      'nav.locations': 'Локации',
      'nav.whereabouts': 'Местонахождение',
      'nav.checkins': 'Чекины',
      'nav.notifications': 'Уведомления',
      'nav.reports': 'Отчеты',
      'nav.settings': 'Настройки',
      'nav.language': 'Язык',
      'dashboard.title': 'Панель администратора',
      'dashboard.subtitle': 'Управляйте бойцами и данными платформы.',
      'dashboard.quickStats': 'Статистика',
      'dashboard.dataOverviewTitle': 'Обзор данных',
      'dashboard.totalFighters': 'Всего бойцов',
      'dashboard.activeFighters': 'Активные бойцы',
      'dashboard.disabledFighters': 'Отключенные бойцы',
      'dashboard.manageFightersHint':
          'В разделе бойцов можно создавать аккаунты и управлять доступом.',
      'dashboard.goToFighters': 'Перейти к бойцам',
      'dashboard.recentFighters': 'Недавно обновленные бойцы',
      'dashboard.noRecentFighters': 'Активности бойцов пока нет.',
      'fighters.title': 'Управление бойцами',
      'fighters.create': 'Создать бойца',
      'fighters.edit': 'Изменить',
      'fighters.save': 'Сохранить',
      'fighters.cancel': 'Отмена',
      'fighters.empty': 'Бойцы пока не добавлены.',
      'fighters.loading': 'Загрузка бойцов...',
      'fighters.error': 'Не удалось загрузить бойцов.',
      'fighters.enabled': 'Включен',
      'fighters.disabled': 'Отключен',
      'fighters.status': 'Статус',
      'fighters.actions': 'Действия',
      'fighters.account': 'Доступ к учетной записи',
      'fighters.createSuccess': 'Учетная запись бойца успешно создана.',
      'fighters.updateSuccess': 'Данные бойца обновлены.',
      'fighters.fullName': 'Полное имя',
      'fighters.dateOfBirth': 'Дата рождения',
      'fighters.selectDate': 'Выберите дату рождения',
      'fighters.invalidDate': 'Выберите корректную дату.',
      'fighters.futureDob': 'Дата рождения не может быть в будущем.',
      'fighters.minAge': 'Боец должен быть не младше 12 лет.',
      'fighters.unrealisticDob': 'Дата рождения выглядит некорректной.',
      'fighters.gender': 'Пол',
      'fighters.genderMale': 'Мужской',
      'fighters.genderFemale': 'Женский',
      'fighters.genderOther': 'Другой',
      'fighters.phone': 'Телефон',
      'fighters.email': 'Email',
      'fighters.address': 'Адрес',
      'fighters.primaryContact': 'Основное контактное лицо',
      'fighters.password': 'Временный пароль',
      'fighters.required': 'Заполните все обязательные поля.',
      'fighters.unknownError': 'Произошла непредвиденная ошибка.',
      'fighters.noResults': 'Нет бойцов, соответствующих текущим фильтрам.',
      'fighters.clearFilters': 'Сбросить фильтры',
      'fighters.searchPlaceholder': 'Поиск по имени, email или телефону',
      'contacts.title': 'Управление контактами',
      'contacts.add': 'Добавить контакт',
      'contacts.edit': 'Редактировать контакт',
      'contacts.name': 'Имя',
      'contacts.phone': 'Телефон',
      'contacts.email': 'Email',
      'contacts.address': 'Адрес',
      'contacts.role': 'Роль',
      'contacts.actions': 'Действия',
      'contacts.search': 'Поиск контактов',
      'contacts.loading': 'Загрузка контактов...',
      'contacts.error': 'Не удалось загрузить контакты.',
      'contacts.empty': 'Контактов пока нет.',
      'contacts.noResults': 'Контакты по текущему фильтру не найдены.',
      'contacts.createSuccess': 'Контакт успешно создан.',
      'contacts.updateSuccess': 'Контакт успешно обновлен.',
      'contacts.unknownError': 'Произошла непредвиденная ошибка.',
      'contacts.roleTrainer': 'Тренер',
      'contacts.roleManager': 'Менеджер',
      'contacts.rolePromoter': 'Промоутер',
      'contacts.roleOther': 'Другое',
      'locations.title': 'Управление локациями',
      'locations.add': 'Добавить локацию',
      'locations.edit': 'Редактировать локацию',
      'locations.name': 'Название',
      'locations.address': 'Адрес',
      'locations.type': 'Тип локации',
      'locations.assignedFighters': 'Назначенные бойцы',
      'locations.actions': 'Действия',
      'locations.search': 'Поиск локаций',
      'locations.loading': 'Загрузка локаций...',
      'locations.error': 'Не удалось загрузить локации.',
      'locations.empty': 'Локаций пока нет.',
      'locations.noResults': 'Локации по текущему фильтру не найдены.',
      'locations.createSuccess': 'Локация успешно создана.',
      'locations.updateSuccess': 'Локация успешно обновлена.',
      'locations.unknownError': 'Произошла непредвиденная ошибка.',
      'locations.typeTesting': 'Локация тестирования',
      'locations.typeTraining': 'Тренировочная локация',
      'locations.typeEvent': 'Локация события',
      'locations.unassigned': 'Не назначено',
      'locations.noFighters': 'Нет бойцов для назначения.',
      'common.comingSoon': 'Скоро',
      'common.retry': 'Повторить',
      'common.loading': 'Загрузка...',
      'comingSoon.contacts':
          'Управление контактами относится к следующему этапу и скоро появится.',
      'comingSoon.locations':
          'Управление локациями относится к следующему этапу и скоро появится.',
      'comingSoon.whereabouts':
          'Мониторинг местонахождения относится к следующему этапу и скоро появится.',
      'comingSoon.checkins':
          'Мониторинг чекинов относится к следующему этапу и скоро появится.',
      'comingSoon.notifications':
          'Мониторинг уведомлений относится к следующему этапу и скоро появится.',
      'comingSoon.reports':
          'Отчеты относятся к следующему этапу и скоро появятся.',
      'comingSoon.settings':
          'Настройки относятся к следующему этапу и скоро появятся.',
    },
    'es': {
      'app.title': 'VADA Admin',
      'auth.loginTitle': 'Inicio de sesión de administrador',
      'auth.email': 'Correo',
      'auth.password': 'Contraseña',
      'auth.login': 'Iniciar sesión',
      'auth.loggingIn': 'Iniciando sesión...',
      'auth.invalidRole': 'Tu cuenta no tiene rol de administrador.',
      'auth.signOut': 'Cerrar sesión',
      'auth.welcome': 'Bienvenido de nuevo',
      'auth.loginFailed': 'No se pudo iniciar sesión. Revisa tus credenciales.',
      'nav.dashboard': 'Panel',
      'nav.fighters': 'Peleadores',
      'nav.contacts': 'Contactos',
      'nav.locations': 'Ubicaciones',
      'nav.whereabouts': 'Paradero',
      'nav.checkins': 'Registros',
      'nav.notifications': 'Notificaciones',
      'nav.reports': 'Reportes',
      'nav.settings': 'Configuración',
      'nav.language': 'Idioma',
      'dashboard.title': 'Panel de administración',
      'dashboard.subtitle': 'Administra peleadores y datos de la plataforma.',
      'dashboard.quickStats': 'Resumen',
      'dashboard.dataOverviewTitle': 'Resumen de datos',
      'dashboard.totalFighters': 'Total de peleadores',
      'dashboard.activeFighters': 'Peleadores activos',
      'dashboard.disabledFighters': 'Peleadores deshabilitados',
      'dashboard.manageFightersHint':
          'Usa gestión de peleadores para crear cuentas y controlar acceso.',
      'dashboard.goToFighters': 'Ir a Peleadores',
      'dashboard.recentFighters': 'Peleadores actualizados recientemente',
      'dashboard.noRecentFighters': 'Aún no hay actividad de peleadores.',
      'fighters.title': 'Gestión de peleadores',
      'fighters.create': 'Crear peleador',
      'fighters.edit': 'Editar',
      'fighters.save': 'Guardar',
      'fighters.cancel': 'Cancelar',
      'fighters.empty': 'No hay peleadores todavía.',
      'fighters.loading': 'Cargando peleadores...',
      'fighters.error': 'No se pudieron cargar los peleadores.',
      'fighters.enabled': 'Habilitado',
      'fighters.disabled': 'Deshabilitado',
      'fighters.status': 'Estado',
      'fighters.actions': 'Acciones',
      'fighters.account': 'Acceso de cuenta',
      'fighters.createSuccess': 'Cuenta de peleador creada correctamente.',
      'fighters.updateSuccess': 'Peleador actualizado correctamente.',
      'fighters.fullName': 'Nombre completo',
      'fighters.dateOfBirth': 'Fecha de nacimiento',
      'fighters.selectDate': 'Selecciona fecha de nacimiento',
      'fighters.invalidDate': 'Selecciona una fecha válida.',
      'fighters.futureDob': 'La fecha de nacimiento no puede ser en el futuro.',
      'fighters.minAge': 'El peleador debe tener al menos 12 años.',
      'fighters.unrealisticDob': 'La fecha de nacimiento no es válida.',
      'fighters.gender': 'Género',
      'fighters.genderMale': 'Masculino',
      'fighters.genderFemale': 'Femenino',
      'fighters.genderOther': 'Otro',
      'fighters.phone': 'Teléfono',
      'fighters.email': 'Correo',
      'fighters.address': 'Dirección',
      'fighters.primaryContact': 'Contacto principal',
      'fighters.password': 'Contraseña temporal',
      'fighters.required': 'Completa todos los campos obligatorios.',
      'fighters.unknownError': 'Ocurrió un error inesperado.',
      'fighters.noResults': 'No hay peleadores que coincidan con los filtros.',
      'fighters.clearFilters': 'Limpiar filtros',
      'fighters.searchPlaceholder': 'Buscar por nombre, correo o teléfono',
      'contacts.title': 'Gestión de contactos',
      'contacts.add': 'Agregar contacto',
      'contacts.edit': 'Editar contacto',
      'contacts.name': 'Nombre',
      'contacts.phone': 'Teléfono',
      'contacts.email': 'Correo',
      'contacts.address': 'Dirección',
      'contacts.role': 'Rol',
      'contacts.actions': 'Acciones',
      'contacts.search': 'Buscar contactos',
      'contacts.loading': 'Cargando contactos...',
      'contacts.error': 'No se pudieron cargar los contactos.',
      'contacts.empty': 'Aún no hay contactos.',
      'contacts.noResults': 'No hay contactos que coincidan con los filtros.',
      'contacts.createSuccess': 'Contacto creado correctamente.',
      'contacts.updateSuccess': 'Contacto actualizado correctamente.',
      'contacts.unknownError': 'Ocurrió un error inesperado.',
      'contacts.roleTrainer': 'Entrenador',
      'contacts.roleManager': 'Manager',
      'contacts.rolePromoter': 'Promotor',
      'contacts.roleOther': 'Otro',
      'locations.title': 'Gestión de ubicaciones',
      'locations.add': 'Agregar ubicación',
      'locations.edit': 'Editar ubicación',
      'locations.name': 'Nombre',
      'locations.address': 'Dirección',
      'locations.type': 'Tipo de ubicación',
      'locations.assignedFighters': 'Peleadores asignados',
      'locations.actions': 'Acciones',
      'locations.search': 'Buscar ubicaciones',
      'locations.loading': 'Cargando ubicaciones...',
      'locations.error': 'No se pudieron cargar las ubicaciones.',
      'locations.empty': 'Aún no hay ubicaciones.',
      'locations.noResults':
          'No hay ubicaciones que coincidan con los filtros.',
      'locations.createSuccess': 'Ubicación creada correctamente.',
      'locations.updateSuccess': 'Ubicación actualizada correctamente.',
      'locations.unknownError': 'Ocurrió un error inesperado.',
      'locations.typeTesting': 'Ubicación de testeo',
      'locations.typeTraining': 'Ubicación de entrenamiento',
      'locations.typeEvent': 'Ubicación de evento',
      'locations.unassigned': 'Sin asignar',
      'locations.noFighters': 'No hay peleadores para asignar.',
      'common.comingSoon': 'Próximamente',
      'common.retry': 'Reintentar',
      'common.loading': 'Cargando...',
      'comingSoon.contacts':
          'La gestión de contactos es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.locations':
          'La gestión de ubicaciones es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.whereabouts':
          'El monitoreo de paradero es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.checkins':
          'El monitoreo de registros es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.notifications':
          'El monitoreo de notificaciones es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.reports':
          'Los reportes son parte de un hito posterior y estarán disponibles pronto.',
      'comingSoon.settings':
          'La configuración es parte de un hito posterior y estará disponible pronto.',
    },
  };

  String tr(String key) {
    final lang = _localizedValues[locale.languageCode];
    final fallback = _localizedValues[_defaultLocaleCode]!;
    return lang?[key] ?? fallback[key] ?? key;
  }
}
