import 'package:flutter/material.dart';

const String _defaultLocaleCode = 'en';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('ja'),
    Locale('ru'),
    Locale('es'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app.title': 'VADA Admin',
      'auth.loginTitle': 'Admin Login',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.login': 'Login',
      'auth.loggingIn': 'Logging in...',
      'auth.invalidRole': 'Your account is not an admin.',
      'auth.signOut': 'Sign out',
      'auth.welcome': 'Welcome back',
      'auth.loginFailed': 'Login failed. Please check credentials.',
      'nav.dashboard': 'Dashboard',
      'nav.fighters': 'Fighters',
      'nav.contacts': 'Contacts',
      'nav.locations': 'Locations',
      'nav.whereabouts': 'Whereabouts',
      'nav.checkins': 'Check-ins',
      'nav.notifications': 'Notifications',
      'nav.reports': 'Reports',
      'nav.settings': 'Settings',
      'nav.language': 'Language',
      'dashboard.title': 'Admin Dashboard',
      'dashboard.subtitle': 'Manage fighters and platform data.',
      'dashboard.quickStats': 'Quick Stats',
      'dashboard.dataOverviewTitle': 'Data Overview',
      'dashboard.totalFighters': 'Total fighters',
      'dashboard.activeFighters': 'Active fighters',
      'dashboard.disabledFighters': 'Disabled fighters',
      'dashboard.manageFightersHint':
          'Use fighter management to create accounts and control access.',
      'dashboard.goToFighters': 'Go to Fighters',
      'dashboard.recentFighters': 'Recently updated fighters',
      'dashboard.noRecentFighters': 'No fighter activity yet.',
      'fighters.title': 'Fighter Management',
      'fighters.create': 'Create Fighter',
      'fighters.edit': 'Edit',
      'fighters.save': 'Save',
      'fighters.cancel': 'Cancel',
      'fighters.empty': 'No fighters found yet.',
      'fighters.loading': 'Loading fighters...',
      'fighters.error': 'Could not load fighters.',
      'fighters.enabled': 'Enabled',
      'fighters.disabled': 'Disabled',
      'fighters.status': 'Status',
      'fighters.actions': 'Actions',
      'fighters.account': 'Account Access',
      'fighters.createSuccess': 'Fighter account created successfully.',
      'fighters.updateSuccess': 'Fighter updated successfully.',
      'fighters.fullName': 'Full Name',
      'fighters.dateOfBirth': 'Date of Birth',
      'fighters.selectDate': 'Select date of birth',
      'fighters.invalidDate': 'Please select a valid date.',
      'fighters.futureDob': 'Date of birth cannot be in the future.',
      'fighters.minAge': 'Fighter must be at least 12 years old.',
      'fighters.unrealisticDob': 'Date of birth looks invalid.',
      'fighters.gender': 'Gender',
      'fighters.genderMale': 'Male',
      'fighters.genderFemale': 'Female',
      'fighters.genderOther': 'Other',
      'fighters.phone': 'Phone',
      'fighters.email': 'Email',
      'fighters.address': 'Address',
      'fighters.primaryContact': 'Primary Contact Person',
      'fighters.password': 'Temporary Password',
      'fighters.required': 'Please fill all required fields.',
      'fighters.unknownError': 'An unexpected error occurred.',
      'common.comingSoon': 'Coming soon',
      'common.retry': 'Retry',
      'common.loading': 'Loading...',
      'comingSoon.contacts':
          'Contacts management is part of a later milestone and will be available soon.',
      'comingSoon.locations':
          'Locations management is part of a later milestone and will be available soon.',
      'comingSoon.whereabouts':
          'Whereabouts monitoring is part of a later milestone and will be available soon.',
      'comingSoon.checkins':
          'Check-in monitoring is part of a later milestone and will be available soon.',
      'comingSoon.notifications':
          'Notification monitoring is part of a later milestone and will be available soon.',
      'comingSoon.reports':
          'Reports are part of a later milestone and will be available soon.',
      'comingSoon.settings':
          'Settings is part of a later milestone and will be available soon.',
    },
    'ja': {
      'app.title': 'VADA 管理',
      'auth.loginTitle': '管理者ログイン',
      'auth.email': 'メールアドレス',
      'auth.password': 'パスワード',
      'auth.login': 'ログイン',
      'auth.loggingIn': 'ログイン中...',
      'auth.invalidRole': 'このアカウントは管理者ではありません。',
      'auth.signOut': 'ログアウト',
      'auth.welcome': 'おかえりなさい',
      'auth.loginFailed': 'ログインに失敗しました。認証情報を確認してください。',
      'nav.dashboard': 'ダッシュボード',
      'nav.fighters': '選手',
      'nav.contacts': '連絡先',
      'nav.locations': 'ロケーション',
      'nav.whereabouts': '所在情報',
      'nav.checkins': 'チェックイン',
      'nav.notifications': '通知',
      'nav.reports': 'レポート',
      'nav.settings': '設定',
      'nav.language': '言語',
      'dashboard.title': '管理ダッシュボード',
      'dashboard.subtitle': '選手とプラットフォームデータを管理します。',
      'dashboard.quickStats': '概要',
      'dashboard.dataOverviewTitle': 'データ概要',
      'dashboard.totalFighters': '選手数',
      'dashboard.activeFighters': '有効な選手',
      'dashboard.disabledFighters': '無効な選手',
      'dashboard.manageFightersHint': '選手管理でアカウント作成とアクセス制御を行えます。',
      'dashboard.goToFighters': '選手管理へ',
      'dashboard.recentFighters': '最近更新された選手',
      'dashboard.noRecentFighters': '選手アクティビティはまだありません。',
      'fighters.title': '選手管理',
      'fighters.create': '選手を作成',
      'fighters.edit': '編集',
      'fighters.save': '保存',
      'fighters.cancel': 'キャンセル',
      'fighters.empty': '選手がまだ登録されていません。',
      'fighters.loading': '選手データを読み込み中...',
      'fighters.error': '選手データを読み込めません。',
      'fighters.enabled': '有効',
      'fighters.disabled': '無効',
      'fighters.status': '状態',
      'fighters.actions': '操作',
      'fighters.account': 'ログインアクセス',
      'fighters.createSuccess': '選手アカウントを作成しました。',
      'fighters.updateSuccess': '選手情報を更新しました。',
      'fighters.fullName': '氏名',
      'fighters.dateOfBirth': '生年月日',
      'fighters.selectDate': '生年月日を選択',
      'fighters.invalidDate': '正しい日付を選択してください。',
      'fighters.futureDob': '生年月日に未来の日付は使えません。',
      'fighters.minAge': '選手は12歳以上である必要があります。',
      'fighters.unrealisticDob': '生年月日が不正です。',
      'fighters.gender': '性別',
      'fighters.genderMale': '男性',
      'fighters.genderFemale': '女性',
      'fighters.genderOther': 'その他',
      'fighters.phone': '電話番号',
      'fighters.email': 'メール',
      'fighters.address': '住所',
      'fighters.primaryContact': '主連絡先',
      'fighters.password': '仮パスワード',
      'fighters.required': '必須項目を入力してください。',
      'fighters.unknownError': '予期しないエラーが発生しました。',
      'common.comingSoon': '近日公開',
      'common.retry': '再試行',
      'common.loading': '読み込み中...',
      'comingSoon.contacts': '連絡先管理は後続マイルストーンで提供予定です。',
      'comingSoon.locations': 'ロケーション管理は後続マイルストーンで提供予定です。',
      'comingSoon.whereabouts': '所在情報監視は後続マイルストーンで提供予定です。',
      'comingSoon.checkins': 'チェックイン監視は後続マイルストーンで提供予定です。',
      'comingSoon.notifications': '通知監視は後続マイルストーンで提供予定です。',
      'comingSoon.reports': 'レポートは後続マイルストーンで提供予定です。',
      'comingSoon.settings': '設定は後続マイルストーンで提供予定です。',
    },
    'ru': {
      'app.title': 'VADA Админ',
      'auth.loginTitle': 'Вход администратора',
      'auth.email': 'Email',
      'auth.password': 'Пароль',
      'auth.login': 'Войти',
      'auth.loggingIn': 'Выполняется вход...',
      'auth.invalidRole': 'У вашей учетной записи нет прав администратора.',
      'auth.signOut': 'Выйти',
      'auth.welcome': 'С возвращением',
      'auth.loginFailed': 'Не удалось войти. Проверьте данные.',
      'nav.dashboard': 'Панель',
      'nav.fighters': 'Бойцы',
      'nav.contacts': 'Контакты',
      'nav.locations': 'Локации',
      'nav.whereabouts': 'Местонахождение',
      'nav.checkins': 'Чекины',
      'nav.notifications': 'Уведомления',
      'nav.reports': 'Отчеты',
      'nav.settings': 'Настройки',
      'nav.language': 'Язык',
      'dashboard.title': 'Панель администратора',
      'dashboard.subtitle': 'Управляйте бойцами и данными платформы.',
      'dashboard.quickStats': 'Статистика',
      'dashboard.dataOverviewTitle': 'Обзор данных',
      'dashboard.totalFighters': 'Всего бойцов',
      'dashboard.activeFighters': 'Активные бойцы',
      'dashboard.disabledFighters': 'Отключенные бойцы',
      'dashboard.manageFightersHint':
          'В разделе бойцов можно создавать аккаунты и управлять доступом.',
      'dashboard.goToFighters': 'Перейти к бойцам',
      'dashboard.recentFighters': 'Недавно обновленные бойцы',
      'dashboard.noRecentFighters': 'Активности бойцов пока нет.',
      'fighters.title': 'Управление бойцами',
      'fighters.create': 'Создать бойца',
      'fighters.edit': 'Изменить',
      'fighters.save': 'Сохранить',
      'fighters.cancel': 'Отмена',
      'fighters.empty': 'Бойцы пока не добавлены.',
      'fighters.loading': 'Загрузка бойцов...',
      'fighters.error': 'Не удалось загрузить бойцов.',
      'fighters.enabled': 'Включен',
      'fighters.disabled': 'Отключен',
      'fighters.status': 'Статус',
      'fighters.actions': 'Действия',
      'fighters.account': 'Доступ к учетной записи',
      'fighters.createSuccess': 'Учетная запись бойца успешно создана.',
      'fighters.updateSuccess': 'Данные бойца обновлены.',
      'fighters.fullName': 'Полное имя',
      'fighters.dateOfBirth': 'Дата рождения',
      'fighters.selectDate': 'Выберите дату рождения',
      'fighters.invalidDate': 'Выберите корректную дату.',
      'fighters.futureDob': 'Дата рождения не может быть в будущем.',
      'fighters.minAge': 'Боец должен быть не младше 12 лет.',
      'fighters.unrealisticDob': 'Дата рождения выглядит некорректной.',
      'fighters.gender': 'Пол',
      'fighters.genderMale': 'Мужской',
      'fighters.genderFemale': 'Женский',
      'fighters.genderOther': 'Другой',
      'fighters.phone': 'Телефон',
      'fighters.email': 'Email',
      'fighters.address': 'Адрес',
      'fighters.primaryContact': 'Основное контактное лицо',
      'fighters.password': 'Временный пароль',
      'fighters.required': 'Заполните все обязательные поля.',
      'fighters.unknownError': 'Произошла непредвиденная ошибка.',
      'common.comingSoon': 'Скоро',
      'common.retry': 'Повторить',
      'common.loading': 'Загрузка...',
      'comingSoon.contacts':
          'Управление контактами относится к следующему этапу и скоро появится.',
      'comingSoon.locations':
          'Управление локациями относится к следующему этапу и скоро появится.',
      'comingSoon.whereabouts':
          'Мониторинг местонахождения относится к следующему этапу и скоро появится.',
      'comingSoon.checkins':
          'Мониторинг чекинов относится к следующему этапу и скоро появится.',
      'comingSoon.notifications':
          'Мониторинг уведомлений относится к следующему этапу и скоро появится.',
      'comingSoon.reports':
          'Отчеты относятся к следующему этапу и скоро появятся.',
      'comingSoon.settings':
          'Настройки относятся к следующему этапу и скоро появятся.',
    },
    'es': {
      'app.title': 'VADA Admin',
      'auth.loginTitle': 'Inicio de sesión de administrador',
      'auth.email': 'Correo',
      'auth.password': 'Contraseña',
      'auth.login': 'Iniciar sesión',
      'auth.loggingIn': 'Iniciando sesión...',
      'auth.invalidRole': 'Tu cuenta no tiene rol de administrador.',
      'auth.signOut': 'Cerrar sesión',
      'auth.welcome': 'Bienvenido de nuevo',
      'auth.loginFailed': 'No se pudo iniciar sesión. Revisa tus credenciales.',
      'nav.dashboard': 'Panel',
      'nav.fighters': 'Peleadores',
      'nav.contacts': 'Contactos',
      'nav.locations': 'Ubicaciones',
      'nav.whereabouts': 'Paradero',
      'nav.checkins': 'Registros',
      'nav.notifications': 'Notificaciones',
      'nav.reports': 'Reportes',
      'nav.settings': 'Configuración',
      'nav.language': 'Idioma',
      'dashboard.title': 'Panel de administración',
      'dashboard.subtitle': 'Administra peleadores y datos de la plataforma.',
      'dashboard.quickStats': 'Resumen',
      'dashboard.dataOverviewTitle': 'Resumen de datos',
      'dashboard.totalFighters': 'Total de peleadores',
      'dashboard.activeFighters': 'Peleadores activos',
      'dashboard.disabledFighters': 'Peleadores deshabilitados',
      'dashboard.manageFightersHint':
          'Usa gestión de peleadores para crear cuentas y controlar acceso.',
      'dashboard.goToFighters': 'Ir a Peleadores',
      'dashboard.recentFighters': 'Peleadores actualizados recientemente',
      'dashboard.noRecentFighters': 'Aún no hay actividad de peleadores.',
      'fighters.title': 'Gestión de peleadores',
      'fighters.create': 'Crear peleador',
      'fighters.edit': 'Editar',
      'fighters.save': 'Guardar',
      'fighters.cancel': 'Cancelar',
      'fighters.empty': 'No hay peleadores todavía.',
      'fighters.loading': 'Cargando peleadores...',
      'fighters.error': 'No se pudieron cargar los peleadores.',
      'fighters.enabled': 'Habilitado',
      'fighters.disabled': 'Deshabilitado',
      'fighters.status': 'Estado',
      'fighters.actions': 'Acciones',
      'fighters.account': 'Acceso de cuenta',
      'fighters.createSuccess': 'Cuenta de peleador creada correctamente.',
      'fighters.updateSuccess': 'Peleador actualizado correctamente.',
      'fighters.fullName': 'Nombre completo',
      'fighters.dateOfBirth': 'Fecha de nacimiento',
      'fighters.selectDate': 'Selecciona fecha de nacimiento',
      'fighters.invalidDate': 'Selecciona una fecha válida.',
      'fighters.futureDob': 'La fecha de nacimiento no puede ser en el futuro.',
      'fighters.minAge': 'El peleador debe tener al menos 12 años.',
      'fighters.unrealisticDob': 'La fecha de nacimiento no es válida.',
      'fighters.gender': 'Género',
      'fighters.genderMale': 'Masculino',
      'fighters.genderFemale': 'Femenino',
      'fighters.genderOther': 'Otro',
      'fighters.phone': 'Teléfono',
      'fighters.email': 'Correo',
      'fighters.address': 'Dirección',
      'fighters.primaryContact': 'Contacto principal',
      'fighters.password': 'Contraseña temporal',
      'fighters.required': 'Completa todos los campos obligatorios.',
      'fighters.unknownError': 'Ocurrió un error inesperado.',
      'common.comingSoon': 'Próximamente',
      'common.retry': 'Reintentar',
      'common.loading': 'Cargando...',
      'comingSoon.contacts':
          'La gestión de contactos es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.locations':
          'La gestión de ubicaciones es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.whereabouts':
          'El monitoreo de paradero es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.checkins':
          'El monitoreo de registros es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.notifications':
          'El monitoreo de notificaciones es parte de un hito posterior y estará disponible pronto.',
      'comingSoon.reports':
          'Los reportes son parte de un hito posterior y estarán disponibles pronto.',
      'comingSoon.settings':
          'La configuración es parte de un hito posterior y estará disponible pronto.',
    },
  };

  String tr(String key) {
    final lang = _localizedValues[locale.languageCode];
    final fallback = _localizedValues[_defaultLocaleCode]!;
    return lang?[key] ?? fallback[key] ?? key;
  }
}
